#
#   /$$$$$   /$$$$$  /$$  /$$ /$$$$$$$$ /$$$$$ /$$$$$  /$$      /$$ /$$      /$$ /$$      
#  /$$_  $$ /$$_  $$| $$ | $$| $$_____/|_ $$_//$$__ $$|  $$    /$$/| $$$    /$$$| $$      
# | $$  \_/| $$ \ $$| $$$| $$| $$       | $$ | $$  \__/ \  $$ /$$/ | $$$$  /$$$$| $$      
# | $$     | $$ | $$| $$$$ $$| $$$$$    | $$ | $$ /$$$$  \  $$$$/  | $$ $$/$$ $$| $$      
# | $$     | $$ | $$| $$ $$$$| $$__/    | $$ | $$|_  $$   \  $$/   | $$  $$$| $$| $$      
# | $$   $$| $$ | $$| $$  $$$| $$       | $$ | $$  \ $$    | $$    | $$\  $ | $$| $$      
# |  $$$$$/|  $$$$$/| $$\  $$| $$       /$$$$|  $$$$$/ /$$ | $$    | $$ \/  | $$| $$$$$$
#  \_____/  \_____/ |__/ \__/|__/      |____/ \_____/ |__/ |__/    |__/     |__/|______/
#                                                                                                   
# =======================================================================================
#           
#                                   Configuration File
#
# =======================================================================================